apiVersion: v1
kind: BuildConfig
metadata:
  name: orhanibm.inventory-management-svc-orhan
  labels:
    app: inventory-management-svc-orhan
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/orhanIBM/inventory-management-svc-orhan.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-oy
        - name: BRANCH
          value: master
